name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml

    with:
      environment: staging
      threads: 100
      run_test: false

    secrets:
      API_TOKEN: ${{ secrets.API_TOKEN }}

  show-workflow-result:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow

    steps:
      - name: Show workflow result
        run: |
          echo "Workflow result: ${{ needs.call-reusable-workflow.outputs.test-result }}"
