name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

      threads:
        required: true
        type: number

jobs:
  reusable-test:
    runs-on: ubuntu-latest

    steps:
      - name: Run reusable workflow
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Threads: ${{ inputs.threads }}"
